PLATFORM = Android
OUTPUT_TYPE = so

PTHREAD = -lm

BIN_PATH = ${ANDROID_NDK_PATH}/toolchains/llvm/prebuilt/linux-x86_64/bin
CC = $(BIN_PATH)/aarch64-linux-android28-clang
STRIP = $(BIN_PATH)/aarch64-linux-android-strip

include Common.mk
